export const SET_FORM = 'SET_FORM';
export const SET_BASEURL = 'SET_BASEURL';
export const RESET_CONFIG = 'RESET_CONFIG';
export const SET_ACCOUNT = 'SET_ACCOUNT';

export const SET_MYDOKUMEN = 'SET_MYDOKUMEN';
export const RESET_MYDOKUMEN = 'RESET_MYDOKUMEN';
export const ADD_MYDOKUMEN = 'ADD_MYDOKUMEN';

export const SET_FAVOURITE_DOKUMEN = 'SET_FAVOURITE_DOKUMEN';
export const RESET_FAVOURITE_DOKUMEN = 'RESET_FAVOURITE_DOKUMEN';
export const ADD_FAVOURITE_DOKUMEN = 'ADD_FAVOURITE_DOKUMEN';

export const SET_PUBLIC_DOKUMEN = 'SET_PUBLIC_DOKUMEN';
export const RESET_PUBLIC_DOKUMEN = 'RESET_PUBLIC_DOKUMEN';
export const ADD_PUBLIC_DOKUMEN = 'ADD_PUBLIC_DOKUMEN';

export const SET_RELATED_DOKUMEN = 'SET_RELATED_DOKUMEN';
export const RESET_RELATED_DOKUMEN = 'RESET_RELATED_DOKUMEN';
export const ADD_RELATED_DOKUMEN = 'ADD_RELATED_DOKUMEN';

export const SET_ACT_VIEW  = 'SET_ACT_VIEW';
export const RESET_ACT_VIEW ='RESET_ACT_VIEW';

export const SET_ACT_SEARCH = 'SET_ACT_SEARCH';
export const RESET_ACT_SEARCH = 'RESET_ACT_SEARCH';
export const DELETE_ACT_SEARCH = 'DELETE_ACT_SEARCH';



